# Generated by Django 4.2 on 2023-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
